CinemapApp_CustomerMVC/Models/Movies.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CinemaApp.CustomerMVC.Models
{
    public class Movies
    {
        [Key]
        public int MoviesID { get; set; }

        public string MovieTitle { get; set; }

        [DisplayFormat(DataFormatString = "{0:dddd dd MMM yyyy}")]
        public DateTime MovieReleaseTime { get; set; }

        public string Duration { get; set; }

        public MAvail MovieAvailable { get; set; }

        // FK
        public virtual ICollection<MovieTimes> MovieTimes { get; set; }
    }

    public enum MAvail
    {
        [Display(Name = "Now Showing")]
        NowShowing,
        [Display(Name = "Coming Soon")]
        ComingSoon
    }
}

CinemapApp_CustomerMVC/Controllers/ATGCinemaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using CinemaApp.AdminConsole;
using CinemaApp.DomainModelEntity;

namespace CinemapApp_CustomerMVC.Controllers
{
    public class ATGCinemaController : Controller
    {
        private const string controllerName = "Admins";
        static HttpResponseMessage response;

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Users users)
        {
            // Check User Valid or not

            response = GlobalVariables.WebApiClient.PostAsJsonAsync($"{controllerName}/Login", users).Result;
            var checkUser = response.Content.ReadAsAsync<Users>().Result;

            if (checkUser == null)
            {
                ViewbagError("Invalid Username or Password");
                return View();
            }

            // If correct, it will store the ID and Username

            Session["CustomerID"] = checkUser.UsersID;
            Session["Username"] = checkUser.Username;
            return RedirectToAction("Movies");
        }

        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignUp(Users users)
        {
            // Check Username and Email got duplicate or not

            response = GlobalVariables.WebApiClient.PostAsJsonAsync($"{controllerName}/GetUser", users).Result;
            var checkUser = response.Content.ReadAsAsync<Users>().Result;

            if (checkUser != null)
            {
                ViewbagError("Username or Email is Duplicated!");
                return View();
            }

            // If no duplicate, it will send to the web api and add the new data

            response = GlobalVariables.WebApiClient.PostAsJsonAsync($"{controllerName}/SignUp", users).Result;
            ViewbagSuccess("Registered Successfully");
            return View();
        }

        public ActionResult Movies()
        {
            // Get all movies from web api and return to the view

            response = GlobalVariables.WebApiClient.GetAsync($"{controllerName}/GetMovies").Result;
            var MoviesList = response.Content.ReadAsAsync<IEnumerable<Movies>>().Result;

            return View(MoviesList);
        }

        public ActionResult MovieShowTimes()
        {
            // Get all movies start time from web api and return to the view

            response = GlobalVariables.WebApiClient.GetAsync($"{controllerName}/GetMovieHalls").Result;
            var MovieTimesList = response.Content.ReadAsAsync<IEnumerable<MovieTimes>>().Result;

            return View(MovieTimesList);
        }

        public ActionResult SelectMovie(int? movieID)
        {
            // Before select a movie, it will check u have sign in or not first

            if (Session["CustomerID"] == null)
            {
                return RedirectToAction("Login");
            }
            // Get all movies start time

            response = GlobalVariables.WebApiClient.GetAsync($"{controllerName}/GetMovieHalls").Result;
            var MovieTimesList = response.Content.ReadAsAsync<IEnumerable<MovieTimes>>().Result;

            // Find which movie start time is related to the selected movie

            var GetTimeList = MovieTimesList.Where(c => c.MoviesID == movieID).ToList();

            return View(GetTimeList);
        }

        public ActionResult MovieDetails(int? movieID)
        {
            // Check the selected movie details

            response = GlobalVariables.WebApiClient.GetAsync($"{controllerName}/GetMovieByID/{movieID}").Result;
            var Movie = response.Content.ReadAsAsync<Movies>().Result;

            return View(Movie);
        }

        public ActionResult SelectedTimeSeats(int? timeID)
        {
            // Before select a movie, it will check u have sign in or not first

            if (Session["CustomerID"] == null)
            {
                return RedirectToAction("Login");
            }

            // Get all the seats which are related to the selected time

            response = GlobalVariables.WebApiClient.GetAsync($"{controllerName}/GetSeatsByTimeID/{timeID}").Result;
            var MovieSeats = response.Content.ReadAsAsync<IEnumerable<MovieSeats>>().Result;

            return View(MovieSeats);
        }

        public ActionResult BuyTicket(int? seatID)
        {
            // Check the selected seat details

            response = GlobalVariables.WebApiClient.GetAsync($"{controllerName}/GetSeatBySeatID/{seatID}").Result;
            var SeatDetails = response.Content.ReadAsAsync<MovieSeats>().Result;

            // If the selected seat is taken thn will go in this if statement

            if (SeatDetails.SeatAvail == SAvail.T)
            {
                ViewbagError("This seat was taken. Please choose another seat.");
                return View(SeatDetails);
            }
            return View(SeatDetails);
        }

        public ActionResult ConfirmPayment(int? seatID)
        {
            var GetUserID = Convert.ToInt32(Session["CustomerID"]);

            // Once clicked confirm buy now it will update the seat details

            response = GlobalVariables.WebApiClient.GetAsync($"{controllerName}/GetSeatBySeatID/{seatID}").Result;
            var SeatDetails = response.Content.ReadAsAsync<MovieSeats>().Result;

            SeatDetails.UsersID = GetUserID;
            SeatDetails.SeatAvail = SAvail.T;

            // Here is update the seat

            response = GlobalVariables.WebApiClient.PutAsJsonAsync($"{controllerName}/UpdateSeatDetail", SeatDetails).Result;
            ViewbagSuccess("Purchase Success! Please come again!");
            return View();
        }

        public ActionResult BookingHistory()
        {
            // Before select a movie, it will check u have sign in or not first

            if (Session["CustomerID"] == null)
            {
                return RedirectToAction("Login");
            }
            var GetUserID = Convert.ToInt32(Session["CustomerID"]);

            // Get all history which are bought from the user

            response = GlobalVariables.WebApiClient.GetAsync($"{controllerName}/GetSeatByUserID/{GetUserID}").Result;
            var SeatDetails = response.Content.ReadAsAsync<IEnumerable<MovieSeats>>().Result;
            
            // If the user doesn't have any history, it will go in this if statement

            if (SeatDetails.Count() == 0)
            {
                ViewbagError("You have no history. Please search for movie and buy ticket.");
                return View();
            }
            return View(SeatDetails);
        }

        public ActionResult Logout()
        {
            return View();
        }

        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        // Non Actions

        [NonAction]
        public void ViewbagError(string Msg)
        {
            ViewBag.Error = Msg;
        }

        [NonAction]
        public void ViewbagSuccess(string Msg)
        {
            ViewBag.Success = Msg;
        }

        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CinemapApp_CustomerMVC/Views/ATGCinema/BookingHistory.cshtml
@model IEnumerable<CinemaApp.DomainModelEntity.MovieSeats>

@{
    ViewBag.Title = "Booking History - ATG Cinema";
    Layout = "~/Views/ATGLayout/ATGHomeLayout.cshtml";
}

@if (Model == null)
{
    <div class="text-danger">
        @{
            if (ViewBag.Error != null)
            {
                <br />
                <p class="alert alert-danger text-center">@ViewBag.Error</p>
            }
        }
    </div>
}
else
{
    <div class="jumbotron">
        <h2 style="text-align:center"><b>Your Booking History</b></h2>
        <br />

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayName("Movie Title")
                </th>
                <th>
                    @Html.DisplayName("Movie Start Time")
                </th>
                <th>
                    @Html.DisplayName("Movie Hall")
                </th>
                <th>
                    @Html.DisplayName("Seat No")
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Amount)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td style="color:blue">
                        @Html.DisplayFor(modelItem => item.MovieTimes.Movies.MovieTitle)
                    </td>
                    <td style="color:blue">
                        @Html.DisplayFor(modelItem => item.MovieTimes.MovieTimeStart)
                    </td>
                    <td style="color:blue">
                        @Html.DisplayFor(modelItem => item.MovieTimes.MovieHallNo)
                    </td>
                    <td style="color:blue">
                        @Html.DisplayFor(modelItem => item.SeatNo)
                    </td>
                    <td style="color:blue">
                       RM @Html.DisplayFor(modelItem => item.Amount)
                    </td>
               
                </tr>
            }

        </table>
    </div>
}

CinemapApp_CustomerMVC/Views/ATGCinema/BuyTicket.cshtml
@model CinemaApp.DomainModelEntity.MovieSeats

@{
    ViewBag.Title = "Buy Ticket - ATG Cinema";
    Layout = "~/Views/ATGLayout/ATGHomeLayout.cshtml";

}

<div class="jumbotron">
    <h2 style="text-align:center">Movie Seat</h2>
    <p></p>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Movie Hall")
            </th>
            <th>
                @Html.DisplayName("Seat No")
            </th>
            <th>
                @Html.DisplayName("Seat Status")
            </th>
            <th>
                @Html.DisplayName("Amount")
            </th>
        </tr>

        <tr>
            <td style="padding-left:37px">
                @Html.DisplayFor(model => model.MovieTimes.MovieHallNo)
            </td>

            <td style="padding-left:30px">
                @Html.DisplayFor(model => model.SeatNo)
            </td>

            @if (Model.SeatAvail == CinemaApp.DomainModelEntity.SAvail.E)
            {
                <td style="padding-left:30px">
                    @Html.DisplayName("Empty")
                </td>
            }
            else
            {
                <td style="padding-left:30px">
                    @Html.DisplayName("Taken")
                </td>
            }

            <td>
                RM @Html.DisplayFor(model => model.Amount)
            </td>
        </tr>

    </table>

    <div class="text-danger">
        @{
            if (ViewBag.Error != null)
            {
                <br />
                <p class="alert alert-danger text-center">@ViewBag.Error</p>
            }
        }
    </div>

    @if (Model.SeatAvail == CinemaApp.DomainModelEntity.SAvail.E)
    {
        <span>
            @Html.ActionLink("Confirm Buy Now", "ConfirmPayment", new { seatID = Model.MovieSeatsID }, new { @class = "w3-btn w3-aqua w3-border w3-border-red w3-round-large" })
        </span>
    }

    <span style="float:right">
        @Html.ActionLink("Back To Seats", "SelectedTimeSeats", new { timeID = Model.MovieTimesID }, new { @class = "w3-btn w3-aqua w3-border w3-border-red w3-round-large" })
    </span>


</div>

CinemapApp_CustomerMVC/Views/ATGCinema/ConfirmPayment.cshtml
@{
    ViewBag.Title = "Confirm Payment - ATG Cinema";
    Layout = "~/Views/ATGLayout/ATGHomeLayout.cshtml";
}

<div class="text-success">
    @{
        if (ViewBag.Success != null)
        {
            <br />
            <h1 class="alert alert-success text-center">@ViewBag.Success</h1>
        }
    }
</div>

CinemapApp_CustomerMVC/Views/ATGCinema/Login.cshtml
@model CinemaApp.DomainModelEntity.Users

@{
    ViewBag.Title = "Sign In - ATG Cinema";
    Layout = "~/Views/ATGLayout/ATGHomeLayout.cshtml";
}

@using (Html.BeginForm("Login", "ATGCinema", FormMethod.Post, new { id = "Login" }))
{
    <div class="form-horizontal img-responsive">
        <div class="jumbotron">

            @*<img src="~/Content/IMG/CafeAnything.jpg" alt="Cafe Anything" class="img-responsive center-block" width="280" height="150" />*@

            <h2 class="text-center">ATG Cinema</h2>

            <div class="form-group text-center">
                <h2>User Login</h2>
            </div>

            <div class="form-group" style="margin-left: 21.4%">
                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Username, new { htmlAttributes = new { required = "required", @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small", placeholder = "Enter Username" } })
                </div>
            </div>

            <div class="form-group" style="margin-left: 21.4%">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { required = "required", @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small", placeholder = "Enter Password", type = "password" } })
                    <span onclick="ShowPass()" class="glyphicon glyphicon-eye-open"></span>
                </div>
            </div>

            <div class="form-group text-center">
                <div class="col-md-offset-2 col-md-10">
                    @Html.TextBox("Login", "Sign In", new { type = "submit", @class = "w3-btn w3-aqua w3-border w3-border-red w3-round-large w3-padding-small" })
                </div>
            </div>

            <div class="text-danger">
                @{
                    if (ViewBag.Error != null)
                    {
                        <br />
                        <p class="alert alert-danger text-center">@ViewBag.Error</p>
                    }
                }
            </div>

        </div>

    </div>
}

<script language="javascript">

    function ShowPass() {
        var x = document.getElementById('Password');

        if (x.type === "password") {
            x.type = "text";

        }

        else {
            x.type = "password";

        }
    }
</script>

CinemapApp_CustomerMVC/Views/ATGCinema/Logout.cshtml
@{
    ViewBag.Title = "Logout";
    Layout = "~/Views/ATGLayout/ATGHomeLayout.cshtml";
}

@{
    Session.Abandon();
}

@{
    Response.Redirect("/ATGCinema/Movies");
}

CinemapApp_CustomerMVC/Views/ATGCinema/MovieDetails.cshtml
@model CinemaApp.DomainModelEntity.Movies

@{
    ViewBag.Title = "Movie Info - ATG Cinema";
    Layout = "~/Views/ATGLayout/ATGHomeLayout.cshtml";
}

<div class="jumbotron">
    <h2>Movie Info</h2>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("Movie Title")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MovieTitle)
            </dd>

            <dt>
                @Html.DisplayName("Release Time")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MovieReleaseTime)
            </dd>

            @if (Model.Duration != "")
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Duration)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Duration)
                </dd>
            }

            <dt>
                @Html.DisplayName("Movie Available")
            </dt>

            @if (Model.MovieAvailable == CinemaApp.DomainModelEntity.MAvail.NowShowing)
            {
                <dd>
                    @Html.DisplayName("Now Showing")
                </dd>
            }
            else
            {
                <dd>
                    @Html.DisplayName("Coming Soon")
                </dd>
            }

        </dl>
    </div>
</div>

CinemapApp_CustomerMVC/Views/ATGCinema/MovieShowTimes.cshtml
@model IEnumerable<CinemaApp.DomainModelEntity.MovieTimes>

@{
    ViewBag.Title = "Show Times - ATG Cinema";
    Layout = "~/Views/ATGLayout/ATGHomeLayout.cshtml";
}

<div class="jumbotron">
    <h2 style="text-align:center"><b>Show Times</b></h2>
    <br />

    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Movie Title")
            </th>
            <th>
                @Html.DisplayName("Movie Start Time")
            </th>
            <th>
                @Html.DisplayName("Movie Hall")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td style="color:blue">
                    @Html.DisplayFor(modelItem => item.Movies.MovieTitle)
                </td>
                <td style="color:blue">
                    @Html.DisplayFor(modelItem => item.MovieTimeStart)
                </td>
                <td style="color:red">
                    @Html.DisplayFor(modelItem => item.MovieHallNo)
                </td>
                <td class="w3-btn w3-aqua w3-border w3-border-red w3-round-large w3-padding-small">
                    @Html.ActionLink("Book Now", "SelectedTimeSeats", new { timeID = item.MovieTimesID })
                </td>
            </tr>
        }

    </table>
</div>

CinemapApp_CustomerMVC/Views/ATGCinema/Movies.cshtml
@model IEnumerable<CinemaApp.DomainModelEntity.Movies>

@{
    ViewBag.Title = "Movies - ATG Cinema";
    Layout = "~/Views/ATGLayout/ATGHomeLayout.cshtml";
}


<div class="jumbotron">
    <h2 style="text-align:center"><b>Movies</b></h2>
    <br />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Movie Title")
            </th>
            <th>
                @Html.DisplayName("Movie Release Time")
            </th>
            <th>
                @Html.DisplayName("Movie Status")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td style="color:blue">
                    @Html.DisplayFor(modelItem => item.MovieTitle)
                </td>
                <td style="color:blue">
                    @Html.DisplayFor(modelItem => item.MovieReleaseTime)
                </td>

                @if (item.MovieAvailable == CinemaApp.DomainModelEntity.MAvail.NowShowing)
                {
                    <td style="color:red">
                        @Html.DisplayName("Now Showing")
                    </td>
                }
                else
                {
                    <td style="color:red">
                        @Html.DisplayName("Coming Soon")
                    </td>
                }

                @if (item.MovieAvailable == CinemaApp.DomainModelEntity.MAvail.NowShowing)
                {
                    <td class="w3-btn w3-aqua w3-border w3-border-red w3-round-large w3-padding-small">
                        @Html.ActionLink("Book Now", "SelectMovie", new { movieID = item.MoviesID })
                    </td>

                    <td class="w3-btn w3-aqua w3-border w3-border-red w3-round-large w3-padding-small">
                        @Html.ActionLink("Movie Info", "MovieDetails", new { movieID = item.MoviesID })
                    </td>
                }
                else
                {
                    <td class="w3-btn w3-aqua w3-border w3-border-red w3-round-large w3-padding-small">
                        @Html.ActionLink("Movie Info", "MovieDetails", new { movieID = item.MoviesID })
                    </td>
                }
            </tr>
        }
    </table>

</div>

CinemapApp_CustomerMVC/Views/ATGCinema/SelectMovie.cshtml
@model IEnumerable<CinemaApp.DomainModelEntity.MovieTimes>

@{
    ViewBag.Title = "Show Times - ATG Cinema";
    Layout = "~/Views/ATGLayout/ATGHomeLayout.cshtml";
}

<div class="jumbotron">
    <h2 style="text-align:center"><b>Show Times</b></h2>
    <br />

    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Movie Title")
            </th>
            <th>
                @Html.DisplayName("Movie Start Time")
            </th>
            <th>
                @Html.DisplayName("Movie Hall")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td style="color:blue">
                    @Html.DisplayFor(modelItem => item.Movies.MovieTitle)
                </td>
                <td style="color:blue">
                    @Html.DisplayFor(modelItem => item.MovieTimeStart)
                </td>
                <td style="color:red">
                    @Html.DisplayFor(modelItem => item.MovieHallNo)
                </td>
                <td class="w3-btn w3-aqua w3-border w3-border-red w3-round-large w3-padding-small">
                    @Html.ActionLink("Select Time", "SelectedTimeSeats", new { timeID = item.MovieTimesID })
                </td>
            </tr>
        }

    </table>
</div>

CinemapApp_CustomerMVC/Views/ATGCinema/SelectedTimeSeats.cshtml
@model IEnumerable<CinemaApp.DomainModelEntity.MovieSeats>

@{
    ViewBag.Title = "Movie Seats - ATG Cinema";
    Layout = "~/Views/ATGLayout/ATGHomeLayout.cshtml";
}

<div class="jumbotron">

    <h2 style="text-align:center"><b>Movie Seats</b></h2>

    <h2 style="text-align:center">
        <b>T: Taken E: Empty</b>
    </h2>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Seat No")
            </th>
            <th>
                @Html.DisplayName("Seat Status")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SeatNo)
                </td>

                @if (item.SeatAvail == CinemaApp.DomainModelEntity.SAvail.E)
                {
                    <td>
                        @Html.DisplayName("Empty")
                    </td>
                }
                else
                {
                    <td>
                        @Html.DisplayName("Taken")
                    </td>
                }

                <td class="w3-btn w3-aqua w3-border w3-border-red w3-round-large w3-padding-small">
                    @Html.ActionLink("Buy Now", "BuyTicket", new { seatID = item.MovieSeatsID })
                </td>
            </tr>
        }

    </table>
</div>

CinemapApp_CustomerMVC/Views/ATGCinema/SignUp.cshtml
@model CinemaApp.DomainModelEntity.Users

@{
    ViewBag.Title = "Sign Up - ATG Cinema";
    Layout = "~/Views/ATGLayout/ATGHomeLayout.cshtml";
}


@using (Html.BeginForm("SignUp", "ATGCinema", FormMethod.Post, new { id = "SignUp" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal img-responsive">
        <div class="jumbotron">

            <h2 class="text-center">Sign Up For ATG Cinema</h2>
            <br />

            <div class="form-group" style="margin-left: 21.4%">
                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Username, new { htmlAttributes = new { required = "required", @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small", placeholder = "Enter Username" } })
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="margin-left: 21.4%">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { required = "required", @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small", placeholder = "Enter Password", type = "password" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    <span onclick="ShowPass()" class="glyphicon glyphicon-eye-open"></span>
                </div>
            </div>

            <div class="form-group" style="margin-left: 21.4%">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { type = "email", required = "required", @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small", placeholder = "Enter Email" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group text-center">
                <div class="col-md-offset-2 col-md-10">
                    @Html.TextBox("SignUp", "Sign up", new { type = "submit", @class = "w3-btn w3-aqua w3-border w3-border-red w3-round-large w3-padding-small" })
                </div>
            </div>

            <div class="text-danger">
                @{
                    if (ViewBag.Error != null)
                    {
                        <br />
                        <p class="alert alert-danger text-center">@ViewBag.Error</p>
                    }

                    if (ViewBag.Success != null)
                    {
                        <br />
                        <p class="alert alert-success text-center">@ViewBag.Success</p>
                    }
                }
            </div>

        </div>
    </div>
}

<script language="javascript">

    function ShowPass() {
        var x = document.getElementById('Password');

        if (x.type === "password") {
            x.type = "text";

        }

        else {
            x.type = "password";

        }
    }
</script>